baseURL = "https://example.com/"
languageCode = "en-us"
title = "ClearCut Media"
enableRobotsTXT = true

[pagination]
  pagerSize = 15

[params]
  description = "Clear media analysis and guides"
  author = "ClearCut Media Team"

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = "daily"
  priority = 0.8

[markup.goldmark.renderer]
  unsafe = true
